import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Providers from './providers';
import { Toaster } from '@/components/ui/sonner';
import RouterConfirm from '@/components/client/router-confirm';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body
          className={cn(
            'flex min-h-screen flex-col items-stretch bg-background font-sans antialiased',
            fontSans.variable
          )}
        >
          <Providers>
            {children}
            <Toaster />
            <RouterConfirm />
          </Providers>
        </body>
      </ClerkProvider>
    </html>
  );
}
